---
- hosts: one-mgmt
  user: root
  roles:
    - iptables
    - { role: yumrepos, repos: [epel, opennebula], when: "one_version != 4.6"}
    - { role: yumrepos, repos: [epel, opennebula46], when: "one_version == 4.6"}
    - one_core
    - one_sunstone
